service:
  description: Spring Weblog

---
spring:
  profiles: development
endpoints:
  jolokia:
    enabled: true  
jolokia:
  config:
    debug: true

---
spring:
  profiles: production
endpoints:
  jolokia:
    enabled: false  
jolokia:
  config:
    debug: false
