service:
  description: Spring Weblog

---
spring:
  profiles: development
endpoints:
  jolokia:
    enabled: true  
jolokia:
  config:
    debug: true

---
spring:
  profiles: production
  datasource:
    url: jdbc:h2:data/weblog
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
endpoints:
  jolokia:
    enabled: false  
jolokia:
  config:
    debug: false
