service:
  description: Spring Weblog
logging:
  file: system.log
---
spring:
  profiles: development
logging:
  path: ./logs/development   
---
spring:
  profiles: production
logging:
  path: ./logs/production
